name: evently_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.2
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
